# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc3420fd25c0ac596b58e971d9f31b5d4f11dd3e02e42aaf8098e02f9faa2d9add1d2fbce002624ceb092d792cb071131fe3df1496eccd4f258d91c50b8c6a5e

test:
  secret_key_base: 38580a6e3ad13b82d9a8530695f481806246be03d006437bdfc4c920ad6f49bb7f30b758e337c9f590e1a8b27db0e0a9712b76c77a9940085993eaf47b92bfb4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
